#!/usr/bin/env python
import bootstrap as bs

bs.fheadline("BS UNMOUNT", desc="unmount partitions")
conf = bs.config()
if not bs.sub("sudo umount %s" % conf.rootpartition):
    pass
    #bs.sub("sudo fuser -km %s" % conf.workdir)