#!/usr/bin/env python
import shlex, subprocess
import bootstrap as bs

bs.fheadline("BS CREATE FILESYSTEM", desc="create root file system")
conf = bs.config()
bs.sub("sudo mke2fs %s" % conf.rootpartition)
