#!/usr/bin/env python
import os.path
import bootstrap as bs

bs.fheadline("BS MOUNT", desc="mount partitions")
conf = bs.config()
if not os.path.exists(conf.workdir):
    bs.sub("mkdir -p %s" % conf.workdir)
bs.sub("sudo mount %s %s" % (conf.rootpartition, conf.workdir))
