#!/usr/bin/env python
import bootstrap as bs


bs.fheadline("BS DEBOOTSTRAP", desc="run debootstrap")
conf = bs.config()
bs.sub("mkdir -p %s" % conf.workdir)
bs.sub("sudo debootstrap --arch %s %s %s %s" % (
    conf.arch, conf.release, conf.workdir, conf.repository))

