#!/usr/bin/env python
import bootstrap as bs

bs.fheadline("BS PREPARE")
conf = bs.config()

sourceslist = """
deb {0} {1} main multiverse restricted universe
deb-src {0} {1} main multiverse restricted universe
deb {0} {1}-updates main multiverse restricted universe
deb-src {0} {1}-updates main multiverse restricted universe
""".format(conf.repository, conf.release).strip()

f = open("sources.list", 'w')

try:
    f.write(sourceslist)
    f.write("\n")
finally:
    f.close()

bs.sub("sudo mv sources.list %s/etc/apt/" % conf.workdir)
