#!/usr/bin/env python
import bootstrap as bs


bs.fheadline("BS PREPARE", desc="configure base system")
conf = bs.config()


bs.tofile("""
#sources
deb {0} {1} main multiverse restricted universe
deb-src {0} {1} main multiverse restricted universe
deb {0} {1}-updates main multiverse restricted universe
deb-src {0} {1}-updates main multiverse restricted universe
""".format(conf.repository, conf.release).strip(),
    bs.workpath(conf, "/etc/apt/sources.list"), sudo=True)  


bs.tofile("""
127.0.0.1 localhost
127.0.1.1 {0}

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodesh
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
""".format(conf.hostname).strip(), bs.workpath(conf, "/etc/hosts"), sudo=True)


bs.tofile("%s" % conf.hostname, bs.workpath(conf, "/etc/hostname"), sudo=True)


bs.tofile("""
{0}         /             ext2    defaults                 0    1
{1}         none          swap    sw                       0    0
""".format(conf.rootpartition, conf.swappartition).strip() + "\n",
bs.workpath(conf, "/etc/fstab"), sudo=True)


envfile = "/00-env"
bs.tofile("""
#!/usr/bin/env bash
cd /
set -o verbose
touch /etc/mtab
mount -a
mount /proc
mount /dev
mount /sys
""".strip(), bs.workpath(conf, envfile), sudo=True, readable=False)
bs.sub("sudo chmod +x %s" % bs.workpath(conf, envfile))


installfile = "/10-install"
bs.tofile("""
#!/usr/bin/env bash
set -o verbose
/00-env
cd /
locale-gen en_US
locale-gen en_US.UTF-8
locale-gen de_DE
locale-gen de_DE@euro
locale-gen de_DE.UTF-8
dpkg-reconfigure locales
apt-get -y update
apt-get -y dist-upgrade
apt-get -y install linux-firmware
apt-get -y install {1}
apt-get -y autoremove
passwd
useradd -G {2} -d /home/{3} -m -s /bin/bash {3}
passwd {3}
umount -a
umount /dev
umount /proc
umount /sys
""".format(
        conf.kernel,
        conf.basepackages,
        conf.groups,
        conf.user),
        bs.workpath(conf, installfile), sudo=True, readable=False)
bs.sub("sudo chmod +x %s" % bs.workpath(conf, installfile))

#kernel and copy firmware here

setupfile = "/20-setup"
bs.tofile("""
#!/usr/bin/env bash
set -o verbose
/00-env
apt-get -y install {0}
""".format(
        conf.packages
        ), bs.workpath(conf, setupfile), sudo=True, readable=False)
bs.sub("sudo chmod +x %s" % bs.workpath(conf, setupfile))


bs.tofile("""
LANG="en_US.UTF-8"          
""".strip(), bs.workpath(conf, "/etc/default/locale"), sudo=True)
