#!/usr/bin/env python
import bootstrap as bs


bs.fheadline("BS PREPARE", desc="configure base system")
conf = bs.config()


bs.tofile("""
#sources
deb {0} {1} main multiverse restricted universe
deb-src {0} {1} main multiverse restricted universe
deb {0} {1}-updates main multiverse restricted universe
deb-src {0} {1}-updates main multiverse restricted universe
""".format(conf.repository, conf.release).strip(),
    bs.workpath(conf, "/etc/apt/sources.list"), sudo=True)  


bs.tofile("""
127.0.0.1 localhost
127.0.1.1 {0}

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
""".format(conf.hostname).strip(), bs.workpath(conf, "/etc/hosts"), sudo=True)


bs.tofile("%s" % conf.hostname, bs.workpath(conf, "/etc/hostname"), sudo=True)


bs.tofile("""
{0}         /             ext2    defaults                 0    1
{1}         none          swap    sw                       0    0
proc             /proc         proc    defaults                 0    0
""".format(conf.rootpartition, conf.swappartition).strip() + "\n",
bs.workpath(conf, "/etc/fstab"), sudo=True)


installfile = "/10-install"
bs.tofile("""
#!/usr/bin/env bash
set -o verbose #echo onset +o verbose
touch /etc/mtab
mount -a
cd /dev
MAKEDEV generic
cd /
locale-gen en_US
locale-gen en_US.UTF-8
locale-gen de_DE
locale-gen de_DE@euro
locale-gen de_DE.UTF-8
dpkg-reconfigure locales
apt-get -y update
apt-get -y dist-upgrade
apt-get -y install linux-firmware linux-firmware-nonfree grub
apt-get -y install {0}
apt-get -y install {1}
dpkg-reconfigure keyboard-configuration
apt-get -y autoremove
passwd
""".format(conf.kernel, bs.removespace(conf.packages).replace(",", " ")),
bs.workpath(conf, installfile), sudo=True, readable=False)


bs.sub("sudo chmod +x %s" % bs.workpath(conf, installfile))


bs.tofile("""
LANG="en_US.UTF-8"          
""".strip(), bs.workpath(conf, "/etc/default/locale"), sudo=True)
