#!/usr/bin/env python
import bootstrap as bs

bs.sub("./00-prepare", echo=False)
bs.sub("./02-info", echo=False)
bs.sub("./20-debootstrap", echo=False)
bs.sub("./30-prepare", echo=False)
bs.sub("./40-chroot-install", echo=False)
